### ISSUE TITLE
Documentation on output files

### ISSUE THREAD

**Issue by GMFranceschini** [dohlee/metheor#5]
Hi, thanks for developing metheor, the performance is impressive.
Is it possible to have a detailed description of the meaning of column outputs?
For example, in the case of PDR I get:

```
chr1	2036142	2036144	0.23076923	20	6
chr1	2036161	2036163	0.24444444	34	11
chr1	2036165	2036167	0.25531915	35	12
```

What are the last two columns? I think this information is not mentioned in the description or in the help. Thank you!

**Comment by dohlee** [comment]
Hi, thanks for trying out our tool.
For now, the documentation has many things to be added including the output format, we'll make it updated soon! 
Feel free to report any other things that would be better to be described in the documentation :)

The last two columns represent the number of concordant sequencing reads (where all the meth. states of CpGs covered by the read are the same) and discordant sequencing reads (where more than one meth. states appear in the read) supporting that specific CpG.
With that in mind, you can notice that the 4th column (PDR) is calculated as 6th / (5th + 6th). Hope this helps!

Best,
Dohoon

**Comment by GMFranceschini** [comment]
Sure! I am very happy to provide feedback, the tools are wonderful, and I love that you used Rust. 
Also, more informative errors might help (badly formatted bed file, wrong paths...). I'll close the issue for now!

**Comment by dohlee** [comment]
Now the README file has the output specification with commit 4d8cb2f9fa0d4361539e168e087210c966fc378b. I'm commenting to this issue just for the reference. Thanks again!

Now I'm working on informative error handling, and hoping to have some updates soon.
