### ISSUE TITLE
Add support for when the genome reference contains IUPAC (e.g., R for A/G, Y for C/T, etc.) codes in them?

### ISSUE THREAD

**Issue by litaifang** [dohlee/metheor#8]
Some versions of the human genome reference has IUPAC codes in them and may not be compatible with these https://github.com/dohlee/metheor/blob/master/src/tag.rs#L72. 
Wondering if you'd like to add support for these cases?

**Comment by dohlee** [comment]
Thank you for the suggestion. Fixed in https://github.com/dohlee/metheor/blob/master/src/tag.rs#L79.
Would you update the package to version 0.1.5 and test it with your data? If it seems okay, I'll close this issue.

Best,
Dohoon

**Comment by litaifang** [comment]
Thanks. Yep version 0.1.5 handles IUPAC now.
